import { ArrowUpCircle, ArrowDownCircle, Trash2, Pencil, Download, RefreshCw } from 'lucide-react';
import { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Button,
} from '@mui/material';
import type { Transaction, UserProfile } from '../../types';
import { formatDate } from '../../utils/formatDate';

interface Props {
  transactions: Transaction[];
  onDelete: (id: string) => void;
  onEdit: (tx: Transaction) => void;
  emptyMessage?: string;
  dateFormat?: UserProfile['dateFormat'];
}
const CATEGORY_COLORS: Record<string, string> = {
  Rent: 'bg-purple-100 text-purple-700',
  Food: 'bg-orange-100 text-orange-700',
  Clothes: 'bg-blue-100 text-blue-700',
  Transport: 'bg-cyan-100 text-cyan-700',
  Utilities: 'bg-yellow-100 text-yellow-700',
  Entertainment: 'bg-pink-100 text-pink-700',
  Salary: 'bg-emerald-100 text-emerald-700',
  Other: 'bg-slate-100 text-slate-700',
};

function exportCSV(transactions: Transaction[], dateFormat: UserProfile['dateFormat']) {
  const header = ['Date', 'Description', 'Category', 'Type', 'Amount'];
  const rows = transactions.map((tx) => [
    formatDate(tx.date, dateFormat),
    `"${tx.description.replace(/"/g, '""')}"`,
    tx.category,
    tx.type,
    tx.amount.toFixed(2),
  ]);
  const csv = [header, ...rows].map((r) => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `flowmint-transactions-${new Date().toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function TransactionList({
  transactions,
  onDelete,
  onEdit,
  emptyMessage = 'No transactions yet. Add your first one!',
  dateFormat = 'MM/DD/YYYY',
}: Props) {
  const [confirmId, setConfirmId] = useState<string | null>(null);

  const handleDeleteClick = (id: string) => setConfirmId(id);
  const handleCancel = () => setConfirmId(null);
  const handleConfirm = () => {
    if (confirmId) onDelete(confirmId);
    setConfirmId(null);
  };

  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
      <div className="p-6 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center">
        <h3 className="font-bold text-slate-800 dark:text-slate-100 text-lg">
          Recent Transactions
        </h3>
        <button
          onClick={() => exportCSV(transactions, dateFormat)}
          disabled={transactions.length === 0}
          className="flex items-center gap-1.5 text-xs font-medium text-slate-500 dark:text-slate-400 hover:text-primary-500 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
        >
          <Download size={14} />
          Export CSV
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50/50 dark:bg-slate-700/50 text-slate-500 dark:text-slate-400 uppercase text-xs font-semibold">
              <th className="px-6 py-4">Transaction</th>
              <th className="px-6 py-4">Category</th>
              <th className="px-6 py-4 text-right">Amount</th>
              <th className="px-6 py-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
            {transactions.length === 0 ? (
              <tr>
                <td colSpan={4} className="px-6 py-12 text-center text-slate-400">
                  {emptyMessage}
                </td>
              </tr>
            ) : (
              transactions.map((tx) => (
                <tr
                  key={tx.id}
                  className="hover:bg-slate-50/50 dark:hover:bg-slate-700/50 transition-colors group"
                >
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      {tx.type === 'income' ? (
                        <ArrowUpCircle className="text-emerald-500" size={20} />
                      ) : (
                        <ArrowDownCircle className="text-rose-500" size={20} />
                      )}
                      <div>
                        <div className="flex items-center gap-2">
                          <p className="font-medium text-slate-900 dark:text-slate-100">
                            {tx.description}
                          </p>
                          {tx.isRecurring && (
                            <span title="Generated by recurring template">
                              <RefreshCw size={12} className="text-primary-500" />
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-400 dark:text-slate-500">
                          {formatDate(tx.date, dateFormat)}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-medium ${
                        CATEGORY_COLORS[tx.category] || 'bg-slate-100 text-slate-600'
                      }`}
                    >
                      {tx.category}
                    </span>
                  </td>
                  <td
                    className={`px-6 py-4 text-right font-semibold ${tx.type === 'income' ? 'text-emerald-600' : 'text-slate-900 dark:text-slate-100'}`}
                  >
                    <div>
                      {tx.type === 'income' ? '+' : '-'}$
                      {tx.amount.toLocaleString(undefined, {
                        minimumFractionDigits: 2,
                        maximumFractionDigits: 2,
                      })}
                    </div>
                    {tx.currency && tx.currency !== 'USD' && (
                      <div className="text-xs text-slate-400 font-normal mt-0.5">
                        (
                        {tx.originalAmount?.toLocaleString(undefined, {
                          minimumFractionDigits: 2,
                          maximumFractionDigits: 2,
                        })}{' '}
                        {tx.currency})
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        onClick={() => onEdit(tx)}
                        className="text-slate-300 dark:text-slate-600 hover:text-primary-500 transition-colors p-2"
                      >
                        <Pencil size={16} />
                      </button>
                      <button
                        onClick={() => handleDeleteClick(tx.id)}
                        className="text-slate-300 dark:text-slate-600 hover:text-rose-500 transition-colors p-2"
                      >
                        <Trash2 size={18} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Dialog open={confirmId !== null} onClose={handleCancel}>
        <DialogTitle>Delete Transaction</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Are you sure you want to delete this transaction? This action cannot be undone.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCancel}>Cancel</Button>
          <Button onClick={handleConfirm} color="error" variant="contained">
            Delete
          </Button>
        </DialogActions>
      </Dialog>
    </div>
  );
}
